# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy()
Song.destroy()

kevin = User.create(username: "Kevin", password: "123")
kerri = User.create(username: "Kerri", password: "corgi")

key1 = Key.create(pitch: "C")
key2 = Key.create(pitch: "C#/Db")
key3 = Key.create(pitch: "D")
key4 = Key.create(pitch: "D#/Eb")
key5 = Key.create(pitch: "E")
key6 = Key.create(pitch: "F")
key7 = Key.create(pitch: "F#/Gb")
key8 = Key.create(pitch: "G")
key9 = Key.create(pitch: "G#/Ab")
key10 = Key.create(pitch: "A")
key11 = Key.create(pitch: "A#/Bb")
key12 = Key.create(pitch: "B")

song1 = Song.create(title: "Never Gonna Give You Up", artist: "Rick Astley", lyrics: "nevergonnagiv nevergonnagiv!", user_id: 1, key_id: 2)
song2 = Song.create(title: "If we hold on, together", artist: "Tina Turner", lyrics: "dreams see us through till foreeeeever", user_id: 2, key_id: 3)
song3 = Song.create(title: "Wonderwall", artist: "Oasis", lyrics: "ur muh wanderwooolllllll", key_id: 10 )
song4 = Song.create(title: "Someday", artist: "The Strokes", lyrics: "somedayyy somedayyyyyy", key_id: 10 )
song5 = Song.create(title: "Rocket Man", artist: "Elton John", lyrics: "and its gonna be a LOng long time", key_id: 11 )
song6 = Song.create(title: "Bohemian Rhapsody", artist: "Queen", lyrics: "mammaaaaaa", key_id: 11 )
song7 = Song.create(title: "Wannabe", artist: "Spice Girls", lyrics: "iwannareallyreallyreallywannaziggasayahhh", key_id: 12 )
song8 = Song.create(title: "I Want it That Way", artist: "Backstreet Boys", lyrics: "i want it thataway", key_id: 12 )
song9 = Song.create(title: "Let it Be", artist: "The Beatles", lyrics: "Let it beeEEeee", key_id: 1 )
song10 = Song.create(title: "Bad Romance", artist: "Lady Gaga", lyrics: "rahrahromamahAHHH", key_id: 1 )
song11 = Song.create(title: "Mr. Brightside", artist: "The Killers", lyrics: "icomminouttamuhcageandivebeendoingJUSTFINE", key_id: 2 )
song12 = Song.create(title: "Summer of '69", artist: "Bryan Adams", lyrics: "u tol me last 5ever", key_id: 3 )
song13 = Song.create(title: "Love Shack", artist: "The B52s", lyrics: "Love shack, baby!", key_id: 4)
song14 = Song.create(title: "Rolling in the Deep", artist: "Adele", lyrics: "we couldda had it ALlALLllllllLLLlLLL", key_id: 4)
song15 = Song.create(title: "The Cave", artist: "Mumford & Sons", lyrics: "*banjo intensifies*", key_id: 5 )
song16 = Song.create(title: "Counting Stars", artist: "One Republic", lyrics: "yeh well be countinngg stars", key_id: 5)
song17 = Song.create(title: "Such Great Heights", artist: "The Postal Service", lyrics: "come down, now!", key_id: 6)
song18 = Song.create(title: "What a Wonderful World", artist: "Louis Armstrong", lyrics: "", key_id: 6)
song19 = Song.create(title: "All Star", artist: "Smash Mouth", lyrics: "NEVER SHINE IF YOU DONT GLOW", key_id: 7)
song20 = Song.create(title: "Float On", artist: "Modest Mouse", lyrics: "I bac my cah into a cap cur teh othere dey", key_id: 7)
song21 = Song.create(title: "Fallin'", artist: "Alicia Keys", lyrics: "I keep on fallin' inanouttt of lovee withaU", key_id: 8)
song22 = Song.create(title: "Good Riddance", artist: "Green Day", lyrics: "there somthing unpredicable an in the end, ok", key_id: 8)
song23 = Song.create(title: "This Charming Man", artist: "The Smiths", lyrics: "haven't got a stitch to weEAaRAer", key_id: 9)
song24 = Song.create(title: "Paint it Black", artist: "The Rolling Stones", lyrics: "Red door = Black door", key_id: 9)
